### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by blackm61** [Isaiahensley/Aquatic-RIG#41]
This issue is for the home page of our website.

Problem? 
         Put the code if you are working in the code:

2. Issue resolution:(Next comments)

3. Status:

For the research issues: 

1. Objective

2. Initial findings

3. Investigation update How the issue should looks like.

**Comment by blackm61** [comment]
![image](https://github.com/Isaiahensley/Aquatic-RIG/assets/143751284/26a19c3a-11f9-431c-85af-593d28f19c7b)


This is some work I've done so far on the home page.

**Comment by blackm61** [comment]
Upcoming Features:

1. Add a summary of our research project below the divider where 'Test' is
2. Define the buttons with their appropriate information and titles, and create functionality for the buttons
3. Describe usage of the website with a usage header and text. For example what each page is about: home page, about page, data-set management page, and the feedback page.

**Comment by blackm61** [comment]
![image](https://github.com/Isaiahensley/Aquatic-RIG/assets/143751284/f8904ba1-3c78-4e26-b2e6-6361c4035e56)

**Comment by blackm61** [comment]
Added functional buttons to the sidebar that link to pages when clicked

**Comment by blackm61** [comment]
Need to work on:

1. Adding a summary of our website and it's use where 'Test' is.
2. Describe usage of the website with a usage header and text. For example what each page is about: home page, about page, data-set management page, and the feedback page.  Basically a section that describes the usage and navigation of the website.

**Comment by Isaiahensley** [comment]
I'm going to close this issue. We created this at the beginning of the semester but this was too broad of an issue.
