### ISSUE TITLE
Feedback Page

### ISSUE THREAD

**Issue by blackm61** [Isaiahensley/Aquatic-RIG#42]
This issue is for the feedback page of our website.

**Comment by spaude11** [comment]
[feedback_report.pdf](https://github.com/Isaiahensley/Aquatic-RIG/files/14107597/feedback_report.pdf)
This is the file generated from feedback form, we will create a database or cloud storage to store these files for later review and upgrade our website

**Comment by spaude11** [comment]
<img width="884" alt="Screenshot 2024-01-30 at 11 37 01 pm" src="https://github.com/Isaiahensley/Aquatic-RIG/assets/53842239/4d2b1384-89ba-48a6-8323-d83bef481f9f">
The feedback page initially will have this UI we will update it as necessary

**Comment by spaude11** [comment]
To configure Google Drive API authentication and share the Google Drive folder with the service account associated with your Streamlit app, follow these steps:

1. Create a Google Cloud Project and Enable Google Drive API:
Go to the Google Cloud Console.
Create a new project or select an existing one.
Enable the Google Drive API for your project.
In the Google Cloud Console, navigate to the "APIs & Services" > "Dashboard."
Click on "+ ENABLE APIS AND SERVICES."
Search for "Google Drive API" and enable it.
2. Create Service Account and Obtain Credentials:
In the Google Cloud Console:
Navigate to "APIs & Services" > "Credentials."
Click on "Create credentials" and select "Service account key."
Choose or create a service account, grant it the necessary permissions (at least Editor role for Google Drive), and create the key in JSON format.
Save the JSON key file securely.
3. Share Google Drive Folder:
Open Google Drive in a web browser.
Create a folder where you want to store feedback.
Right-click on the folder and click on "Share."
Share the folder with the email address associated with the service account (found in the JSON key file).
4. Update Streamlit App Code:
Update your Streamlit app code to use the credentials from the JSON key file and specify the folder ID where feedback will be stored.

Here's a modification to the upload_to_google_drive function:

python
Copy code
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

def upload_to_google_drive(pdf_filename, folder_id):
    gauth = GoogleAuth()
    
    # Load credentials from the JSON key file
    gauth.credentials = ServiceAccountCredentials.from_json_keyfile_name('path/to/your/credentials.json', ['https://www.googleapis.com/auth/drive'])
    
    # Start PyDrive with the loaded credentials
    drive = GoogleDrive(gauth)

    # Upload the PDF to Google Drive in the specified folder
    pdf_file = drive.CreateFile({'title': pdf_filename, 'parents': [{'id': folder_id}]})
    pdf_file.Upload()

    return pdf_file['id']
Replace 'path/to/your/credentials.json' with the actual path to your JSON key file.

5. Deploy Updated App:
Deploy your updated Streamlit app to your server, ensuring that the new credentials file is available on the server.

Now, your Streamlit app should authenticate with the Google Drive API using the service account, and the uploaded PDFs will be stored in the specified Google Drive folder.

Remember to handle sensitive information, such as the JSON key file, securely on your server. Additionally, ensure that your service account has the necessary permissions to access and modify the Google Drive folder.


This is what I found from chatgpt we will research more and work based on these.

**Comment by spaude11** [comment]
When designing a feedback form for your NC files data visualization website, you want to gather information that will help you understand users' experiences, preferences, and any issues they may have encountered. Here are some key elements you can include in your feedback form:
We might include some functions that will directly determine who is using our website as well as their

**Comment by rpeters47** [comment]
**Overall Satisfaction Rating**: Add a rating scale (e.g., 1 to 5 stars) where users can rate their overall satisfaction with the website.

Specific Feedback Fields:

1. **Ease of Use**: Ask users to rate how easy it was to navigate the website and interact with the data visualization tools.
2. **Design and Layout**: Gather feedback on the website's design, aesthetics, and organization.
3. **Performance**: Inquire about the website's loading speed, responsiveness, and any technical issues users may have encountered.
4. **Data Visualization Quality**: Assess users' opinions on the effectiveness and clarity of the NC files data visualization.
5. **Features and Functionality**: Allow users to comment on specific features they found useful or lacking.
6. **Suggestions for Improvement**: Provide an open-ended field where users can share any suggestions or ideas for enhancing the website.
7. **User Demographics**: Optionally, include demographic questions such as age range, occupation, or industry to better understand your website's user base.
8. **User Experience**: Include questions or fields where users can describe their experience using the website in their own words. This can provide valuable insights into usability issues or positive aspects of the website.
9. **Contact Information (Optional)**: Offer users the option to provide their email address or contact information if they would like a response or follow-up regarding their feedback.
10. **Privacy and Data Usage**: Include a brief statement about how you will use the feedback data and ensure users that their responses will be kept confidential and used only for improving the website.

**Comment by spaude11** [comment]
Looks good, lets work together in building good feedback page.

**Comment by Isaiahensley** [comment]
I'm going to close this issue. We created this at the beginning of the semester but this was too broad of an issue.
