### ISSUE TITLE
Dataset Management Page

### ISSUE THREAD

**Issue by Isaiahensley** [Isaiahensley/Aquatic-RIG#44]
I wasn't able to make any progress this week for the Dataset Management Page. However, last semester I created a separate github repository to make an example streamlit website for uploading and visualizing .nc files. This code is not modular and currently only works for the specific dataset I used. I plan to integrate something similar into my feature branch and add more features.

https://github.com/Isaiahensley/SteamlitTest

Upcoming Features:
1)  Functionality to configure how the dataset can be visualized. Select which data values you want visualized out of the ones listed in the .nc file.
2) Allow users to have a dataset laid out in a csv file to have a better understanding of the data being represented. You can view this data similar to how it would look in excel.
3) Allow users to select and upload multiple datasets.
4) Make the code modular for varying datasets.

**Comment by Isaiahensley** [comment]
h

**Comment by Isaiahensley** [comment]
![image](https://github.com/Isaiahensley/Aquatic-RIG/assets/143129356/7d2b967e-57a0-4afb-ae15-71a63776b46e)
![image](https://github.com/Isaiahensley/Aquatic-RIG/assets/143129356/573ebf17-a54c-47c6-b3f1-7cce42afb653)

**Features added:**
1) File uploader
2) Selectbox for choosing visualization options
3) Sliders for time and depth

**Comment by Isaiahensley** [comment]
![image](https://github.com/Isaiahensley/Aquatic-RIG/assets/143129356/e04081b8-33b2-4883-beeb-91e2e143caf2)

**Features added:**

1. Checks for file upload
2. Lists out information from the NC file uploaded. This was mainly to make sure data could be read properly from uploaded 
files.

pushed changes to https://github.com/Isaiahensley/Aquatic-RIG/tree/feature/dataset-management-page

**To Do:**

1. Separate data to make it more manageable to visualize
2. Create an interactive matplotlib scatterplot from the uploaded file

**Comment by spaude11** [comment]
Looks good
