### ISSUE TITLE
March Sprint Retrospective

### ISSUE THREAD

**Issue by Isaiahensley** [Isaiahensley/Aquatic-RIG#47]
Due Friday March 29

**Comment by spaude11** [comment]
What went well: 
Timely standup submission and accurate issue creation. 
Issues such as [] finished in deadline. 


What didn't go well: 
Issues completion and task updates were not upto dates for some issues[]

Action Items: 
Make issues for finalizing the product

**Comment by Isaiahensley** [comment]
**What went well:** 

- StreamLit Sharing runs our website directly from our Github repository which made it easy to get our demo running [demo](https://aquaticrig-develop.streamlit.app/)

- Last month we had trouble figuring out how to use gitflow. This has been resolved and it has been much easier to test everyone's feature branches and get them working together in our develop branch in preparation for the demo.

---------------------------------------------------------------

**What didn't go well:** 

- I was not able to prioritize issues that would have helped the team. For example: Richard wanted me to fix the dropbox code so that it worked with the changes he made to the feedback page this month https://github.com/users/Isaiahensley/projects/3?pane=issue&itemId=54743135. 
However, I never helped him with this so currently the dropbox still does not work and we cant test it. 

- I spent time getting gifs working on our homepage but this issue should have initially been given to Maria. Eventually I handed this issue off to Maria. I could have been working on something else instead like helping Isaiah test the changes he made to the Dataset Management page or fixing our dropbox for the feedback page.
https://github.com/Isaiahensley/Aquatic-RIG/issues/60

- Maria was having issues creating the homepage because our story board last semester didn't translate well with the limitations we have using streamlit to build our website. This also led to confusion for things to fill the page with and prevented her from completing issues on time.

- Richard not being able to complete the [how-to-use section](https://github.com/users/Isaiahensley/projects/3/views/6?pane=issue&itemId=54531998) due to Isaiah's delayed Dataset management page completion. 

- We closed Richards feedback page issue but then realized we need to make the questions anonomyous and make sure we don't made the questions sound biased.

-------------------------------------------------------------

**Action Items:** 

- Complete the DropBox for Richards feedback page
- Create issues for additional changes needed for the feedback page
- Make sure everyone is completing issues on time especially if it prevents others from completing issues.
- Have more team discussion.
