### ISSUE TITLE
January Sprint Retrospective

### ISSUE THREAD

**Issue by blackm61** [Isaiahensley/Aquatic-RIG#50]
Due January 31. This is our retrospective for the month of January.

**Comment by blackm61** [comment]
Feedback from Keyvan about our standups: 


I appreciate everyone being punctual for our recent standup session and submitting your notes on time. However, there are critical areas that need immediate attention and improvement.

**Richard**: Your standup notes **did not accurately reflect your actual contributions**. It is imperative to have a clear understanding and record of what you have accomplished. This discrepancy is concerning and reflects a need for better self-organization and awareness. Your score is 80%.

**Sudeep (Team Lead)**: As the team lead and a graduate student, I expected more initiative in **setting up a sprint for the team**. The lack of a structured sprint has resulted in team members working on disparate issues without clear direction. It is crucial to develop a sprint and ensure the team adheres to it throughout January. Additionally, **start planning the sprint for February** to maintain a steady workflow. Your score is 75%.

**Isaiah**: While your enthusiasm to show your work is appreciated, the purpose of the standup is to **discuss and reflect on your standup notes**. It's important to stick to the agenda and communicate effectively about your progress and challenges. Your score is 85%.

**Maria**: You have shown excellent commitment to your task, working diligently on the home page. Your focused approach and **clear understanding of your responsibilities** are commendable. Your score is 100%.

**Comment by spaude11** [comment]
**January RetroSpective: 
What went well:** 
Gathering necessary tools for actual development like Pycharm, Streamlit cloud hosting credentials, setting up Github repository was swift. 
The initial development of practice pages provided the basic structure for Website development.
Team collaboration

**What didn't go as planned:** 
Team meeting couldn't go as well prepared which created miscommunication and issues.
Testing environment setup hasn't been going as planned.
Functionality division needs more refinement

**Action Items:** 
Meeting every week one day for discussion. 
Getting more familiar with the Testing methods for code.

**Comment by rpeters47** [comment]
January Retrospective
What Went Well:
1. Made progress on the website.
What Didn't Go As Planned:
1. Lack of communication.
Actions Needed:
1. Better communication.

**Comment by Isaiahensley** [comment]
**January Retrospective**

**What Went Well:**
1. We are on track to have a website demo by the end of March

**What Didn't Go As Planned:**
1. Struggled planning out our first month of website development
4. Issues figuring out how we can divide work amongst our team
5. We did not spend a lot of time creating our Slack standups
6. Confusion on how to use Streamlit in Pycharm with our repository and push changes to GitHub
7. Very little communication outside of class and very few text messages with our group
8. Team members made little effort to share the progress they made with the group
9. Progress made was not reflected well in our issues
10. We were late to outline a sprint for January

**Actions Needed:**
1. We need to meet with each other more often outside of class
3. More motivation is needed from team members to make progress and show their work
4. We must meet at least the night before class and create standups.
5. I want to help everyone better understand how we will use our repository with Pycharm and understand the tools needed for making the website
6. Issues need to be regularly updated to reflect work done accurately

**Comment by Isaiahensley** [comment]
@rpeters47 
You need to be a lot more descriptive with your retrospective. 

@spaude11  
You should have things listed similar to what I posted and if possible, add more things that went well and badly.

**Comment by spaude11** [comment]
January RetroSpective:
What went well:

1. Gathering necessary tools for actual development like Pycharm, Streamlit cloud hosting credentials, and setting up the Github repository was swift.
2. The initial development of practice pages provided the basic structure for Website development.
3. Team collaboration
4. Learning GitHub and git commands. 
5. Completed the practice assignment Isaiah made, which helped in familiarizing the streamlit. 

What didn't go as planned:

1. Lack of slack stand-up presentation preparation. 
2. Late to utilize sprint
3. Little to no communication outside the class
4. Issue naming didn't match the end goal. 
5. Team meeting couldn't go as well prepared which created miscommunication and issues.
6. The testing environment setup hasn't been going as planned.
7. Functionality division needs more refinement


Action Items:

1. Meeting every week one day for discussion.
2. More precision in issue naming and definition for an end goal.
3. More clean-up in standup submission. 
4. Getting more familiar with the Testing methods for code.

**Comment by rpeters47** [comment]
**January Retrospective**

**What Went Well:**
1. We had after-class meetings via Discord and Zoom.
2. Progress on the website is going good.

**What Went Wrong:**
1. I had little to no knowledge on how to create websites using Python.  This meant that I was unable to make much progress on the feedback page.
2. I had trouble focusing on the project.
3. Kept making last minute stand-ups.

**Actions Needed:**
1. Work on stand-ups earlier.
2. Work on getting better at focusing.

**Comment by blackm61** [comment]
January Retrospective

What Went Well:

Website development is going well and we are on track to have a website demo by the end of March

What Didn't Go As Planned:

Struggled planning out our first month of website development. No sprint. 

Issues figuring out how we can divide work amongst our team. Again, no sprint planning.

Some members stand ups are not clear and honest

Actions Needed:

Must plan monthly sprints.

We should meet the night before class and create stand ups.

Slack stand ups must be accurate and concise. If you did not do any work on an issue-- state in your standup that you didn't get any work done. If you did not add any progress to any issue-- state that you did not get any work done.
