### ISSUE TITLE
Heat Map Visualization

### ISSUE THREAD

**Issue by Isaiahensley** [Isaiahensley/Aquatic-RIG#56]
**This Heat Map Visualization feature will allow users to have specified variables visualized on a Heat Map, more specifically, a pcolormesh() in matplotlib. This will be one of the options users have when visualizing data from an uploaded netCDF4 file.**

The first Visualization I plan to add to the dataset management page will be a heat map. I've made some progress and this is a good example of what it will look like:

![image](https://github.com/Isaiahensley/Aquatic-RIG/assets/143129356/8f685b8f-168d-4f2c-9bf4-5191ac6749d5)

Currently, this heat map shows temperature values at different depths in the water. At the moment, the time dimension is not adjustable.

![image](https://github.com/Isaiahensley/Aquatic-RIG/assets/143129356/156ecdd5-bbea-479d-84a5-b945aa95fe2c)

This issue is not complete and still has some features that need to be implemented. The idea is that you will select that you want the data visualized as a "Heat Map" and then it will ask which variable you would like to visualize. In my previous example, I chose to visualize "temp" which are the temperature readings gathered at various locations in the ocean. You will be able to select other options. You will then have a slider for time and depth that adjusts the time and depth you want to have the data visualize. The Heat Map will change in real time depending on the slider selection.

I will commit these features once it is complete.

**Comment by blackm61** [comment]
I think this would look better smaller on the website. It's currently too big to see all at once on the page

**Comment by spaude11** [comment]
Looks good.

**Comment by Isaiahensley** [comment]
.

**Comment by Isaiahensley** [comment]
.

**Comment by spaude11** [comment]
To enhance the clarity and productivity of our standups, I require that all issues presented adhere to a detailed format, as exemplified below. This approach will not only improve our understanding of each issue but also streamline our collaborative efforts to address them.

Sample Format for Issue Presentation:

Description: Clearly state the problem, including any specific error messages or unexpected behavior. Detail the context in which the issue occurs.

Steps to Reproduce: Provide a step-by-step guide on how to encounter the issue, making it easier for team members to replicate and understand the problem.

Expected vs. Actual Behavior: Describe what the expected behavior should be and how the actual outcome deviates from this expectation.

Code Snippets: Include relevant code snippets or configurations that relate to the issue, aiding in a more technical understanding and discussion.

Environment Details: Mention the operating system, software versions, and any other environment specifics that could influence the issue.

For Issue Resolution:

Detail the investigation, proposed changes, and the outcome, ensuring to describe how the resolution addresses the issue. Include modified code snippets and a summary of the impact of these changes.


Structure your issue like the format above, include description, Steps to reproduce, Expected vs Actual Behaviour, Code Snippets, Environment Details, Issue Resolution

**Comment by Isaiahensley** [comment]
> To enhance the clarity and productivity of our standups, I require that all issues presented adhere to a detailed format, as exemplified below. This approach will not only improve our understanding of each issue but also streamline our collaborative efforts to address them.
> 
> Sample Format for Issue Presentation:
> 
> Description: Clearly state the problem, including any specific error messages or unexpected behavior. Detail the context in which the issue occurs.
> 
> Steps to Reproduce: Provide a step-by-step guide on how to encounter the issue, making it easier for team members to replicate and understand the problem.
> 
> Expected vs. Actual Behavior: Describe what the expected behavior should be and how the actual outcome deviates from this expectation.
> 
> Code Snippets: Include relevant code snippets or configurations that relate to the issue, aiding in a more technical understanding and discussion.
> 
> Environment Details: Mention the operating system, software versions, and any other environment specifics that could influence the issue.
> 
> For Issue Resolution:
> 
> Detail the investigation, proposed changes, and the outcome, ensuring to describe how the resolution addresses the issue. Include modified code snippets and a summary of the impact of these changes.
> 
> Structure your issue like the format above, include description, Steps to reproduce, Expected vs Actual Behaviour, Code Snippets, Environment Details, Issue Resolution

I made an edit to my post that follows this format. Thank you!

**Comment by spaude11** [comment]
I like the way you formatted the issue. Its really nice. I will use this as a model for the next time whenever I will create and work on issue.

**Comment by Isaiahensley** [comment]
**Description:**
The heatmap is fully functional and modular for various nc files uploaded to the website. Now that this issue is complete it should be easy to add additional visualization options.

**Steps to Reproduce:**
1) Upload .nc file(s)
2) Select "Heat Map" as the Visualization Option
3) Choose a variable for analysis
4) Adjust time and depth to have the heat map updated for the specified dimensions.

**Expected vs. Actual Behavior:**
Everything works as expected but the UI for this page will need to be adjusted. I was able to make the graph smaller. Previously it was too large to be viewed on the website without scrolling. I was also able to remove the white background which filled up most of the page.

**Code Snippets:**
```
import streamlit as st
import netCDF4 as nc
from collections import defaultdict
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
from io import BytesIO

def datasetmanagement_page():
    st.title("Dataset Management")

    # File uploader for multiple .nc files in the sidebar
    files_upload = st.file_uploader("Upload datasets", type=["nc"], accept_multiple_files=True)

    # Initialize a mapping of datetime strings to their corresponding file names
    datetime_to_file_map = defaultdict(list)

    depth_levels = None  # Variable to store the number of depth levels

    if files_upload:
        all_datetime_strings = []
        variables_not_dimensions = []

        for uploaded_file in files_upload:
            nc_file = nc.Dataset('in-memory', memory=uploaded_file.getvalue(), diskless=True)

            # Extract depth information from the first file
            if 'depth' in nc_file.dimensions and depth_levels is None:
                depth_dim = nc_file.dimensions['depth']
                depth_levels = len(depth_dim)  # Store the number of depth levels

            time_var = nc_file.variables['time']
            time_units = time_var.units
            datetimes = nc.num2date(time_var[:], units=time_units)

            for dt in datetimes:
                dt_str = str(dt)
                all_datetime_strings.append(dt_str)
                datetime_to_file_map[dt_str].append(uploaded_file.name)

            # Identify variables that are not dimensions
            if not variables_not_dimensions:  # If not already determined
                for var_name, variable in nc_file.variables.items():
                    if var_name not in nc_file.dimensions:
                        variables_not_dimensions.append(var_name)

            nc_file.close()

        # Display time select box
        if all_datetime_strings:
            selected_datetime_str = st.sidebar.selectbox(
                "Time:",
                options=all_datetime_strings,
                index=0  # Default to the first option
            )

            #associated_files = datetime_to_file_map[selected_datetime_str]
            #st.write(f"Selected datetime: {selected_datetime_str}")
            #for file in associated_files:
                #st.write(f"From file: {file}")
        else:
            st.sidebar.write("No datetime values found.")

        # Display depth slider if depth information is available
        if depth_levels is not None:
            selected_depth = st.sidebar.slider("Depth", 0, depth_levels - 1, value=0)
            #st.write(f"Selected depth level: {selected_depth}")
        else:
            st.sidebar.write("No depth information available.")

        # If time and depth exists...
        if all_datetime_strings:
            if depth_levels is not None:
                selected_visualization = st.sidebar.selectbox(
                    "Visualization Option:",
                    options=["None", "Heat Map", "something else"],
                    index=0  # Default to the first option
                )
                if selected_visualization == "Heat Map":
                    if variables_not_dimensions:
                        selected_variable = st.sidebar.selectbox(
                            "Choose a variable for analysis:",
                            options=["None"] + variables_not_dimensions
                        )
                        # At the point where you decide to call heatmap() if selected_variable is not "None":
                        # Assuming 'uploaded_file' is a BytesIO object from 'files_upload'
                        # Instead of passing 'filename', pass the BytesIO object or its content

                        if selected_variable != "None":
                            associated_files = datetime_to_file_map[selected_datetime_str]
                            if associated_files:
                                # filename variable here would be misleading, it's actually the file content
                                file_content = next(
                                    (file.getvalue() for file in files_upload if file.name == associated_files[0]),
                                    None)

                                if file_content:
                                    # Call the heatmap function with the file content
                                    heatmap(file_content, selected_datetime_str, selected_depth, selected_variable)



                    else:
                        st.sidebar.write("No variable information available.")


def parse_datetime(datetime_str):
    # List of potential datetime formats
    datetime_formats = [
        "%Y-%m-%d %H:%M:%S.%f",  # Format with full precision
        "%Y-%m-%d %H:%M:%S",  # Format without microseconds
        "%Y-%m-%d %H:%M",  # Format without seconds
        "%Y-%m-%d %H",  # Format without minutes and seconds
        "%Y-%m-%d",  # Date only, no time
        # Add more formats as needed
    ]

    # Try parsing the datetime string with each format
    for fmt in datetime_formats:
        try:
            return datetime.strptime(datetime_str, fmt)
        except ValueError:
            continue  # Try the next format

    # Handle the case where none of the formats matched
    raise ValueError(f"Date format for '{datetime_str}' is not supported.")


def heatmap(file_content, datetime_str, depth, variable):
    # Load the NetCDF file from BytesIO object
    nc_file = nc.Dataset('in-memory', memory=file_content)

    try:
        # Convert the selected datetime string back to a datetime object
        selected_datetime = parse_datetime(datetime_str)

        # Find the index of the selected time
        time_var = nc_file.variables['time']
        time_units = time_var.units
        selected_time_index = np.where(nc.num2date(time_var[:], units=time_units) == selected_datetime)[0][0]

        # Access the data for the selected variable
        data = nc_file.variables[variable]

        # Assuming the data structure is [time, depth, lat, lon]
        selected_data = data[selected_time_index, depth, :, :]

        # Get latitude and longitude values for plotting
        lat = nc_file.variables['lat'][:]
        lon = nc_file.variables['lon'][:]

        # Create the heatmap with a smaller figure size
        # Adjust the figsize (width, height) as needed to fit your Streamlit layout
        fig, ax = plt.subplots()  # Example: Smaller figure size
        c = ax.pcolormesh(lon, lat, selected_data, cmap='coolwarm')
        #ax.set_title(f'{variable} at depth {depth} on {datetime_str}')
        ax.set_xlabel('Longitude')
        ax.set_ylabel('Latitude')
        fig.colorbar(c, ax=ax, label=variable)

        fig.tight_layout(pad=1.0)

        buf = BytesIO()
        fig.savefig(buf, format="png", transparent=True)
        st.image(buf, width=1080)

        # Display the plot
        #st.pyplot(fig)
    except Exception as e:
        st.error(f"Error generating heatmap: {e}")
    finally:
        nc_file.close()
```


**Screenshots:**
![image](https://github.com/Isaiahensley/Aquatic-RIG/assets/143129356/f077ee17-63f0-404c-93fd-41a32bd8f778)

**Environment Details:**
Pycharm (python 3)
localhost streamlit sharing website

**For Issue Resolution:**
The issue can be closed.
