### ISSUE TITLE
DropBox Integration for Feedback Storage

### ISSUE THREAD

**Issue by spaude11** [Isaiahensley/Aquatic-RIG#58]
We will use this ticket for uploading our feedback pdf file into specific dropbox file

The initial plan of using google drive is changed to dropbox.

**Comment by spaude11** [comment]
credentials = service_account.Credentials.from_service_account_file('service_account_key.json')
drive_service = build('drive', 'v3', credentials=credentials)

def upload_to_google_drive(pdf_filename):
    file_metadata = {
        'name': pdf_filename
    }
    media = MediaFileUpload(pdf_filename, mimetype='application/pdf')
    file = drive_service.files().create(body=file_metadata, media_body=media, fields='id').execute()
    return file.get('id'). 
    
    I will work on integrating the google api and setup this is just the basic code that i will use.

**Comment by Isaiahensley** [comment]
> credentials = service_account.Credentials.from_service_account_file('service_account_key.json') drive_service = build('drive', 'v3', credentials=credentials)
> 
> def upload_to_google_drive(pdf_filename): file_metadata = { 'name': pdf_filename } media = MediaFileUpload(pdf_filename, mimetype='application/pdf') file = drive_service.files().create(body=file_metadata, media_body=media, fields='id').execute() return file.get('id').
> 
> ```
> I will work on integrating the google api and setup this is just the basic code that i will use. 
> ```

You'll want to explain why you put this code in here and what it does.

**Comment by spaude11** [comment]
BadInputError: BadInputError('d02f7149882a486d93f493de0057e4bd', 'Error in call to API function "files/upload": Your app is not permitted to access this endpoint because it does not have the required scope \'files.content.write\'. The owner of the app can enable the scope for the app using the Permissions tab on the App Console.')

**Comment by spaude11** [comment]
This "Your app is not permitted to access this endpoint" error indicates that the access token you're using to make the call does not have the necessary scope needed for calling that particular endpoint. As indicated by the error message in this case, the app would need the "files.metadata.read" scope.

You can add it via the "Permissions" tab on the app's info page on [the App Console](https://www.dropbox.com/developers/apps). Then you can get a new access token with that scope added and use that new access token to make this API call.
[https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Integrated-creation-folder/td-p/470963](url)

**Comment by spaude11** [comment]
> This "Your app is not permitted to access this endpoint" error indicates that the access token you're using to make the call does not have the necessary scope needed for calling that particular endpoint. As indicated by the error message in this case, the app would need the "files.metadata.read" scope.
> 
> You can add it via the "Permissions" tab on the app's info page on [the App Console](https://www.dropbox.com/developers/apps). Then you can get a new access token with that scope added and use that new access token to make this API call. [https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Integrated-creation-folder/td-p/470963](url)

This helped me solve the issue

**Comment by Isaiahensley** [comment]
This is great and I'm glad we are formatting our issues this way. It makes understanding everyone's progress a lot easier. I'll look at this with you later today.

**Comment by spaude11** [comment]
**Description:** 
The objective of this issue was to upload the feedback file name as current date time rather than email address. 

**Outcome**
Expective the  file named should be in Y_M_D_H_M_S format.

<img width="545" alt="Screenshot 2024-04-03 at 12 37 40 PM" src="https://github.com/Isaiahensley/Aquatic-RIG/assets/53842239/c53fa106-1087-410d-a909-1cb40b08c2d7">



**Code Snippets:** 

```
   def upload_file(self, file_data, file_name, st):
        try:
            current_time = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
            # Construct the new filename with the user's email
            new_file_name = f"feedback_report_{current_time}.pdf"

            # Upload the file to Dropbox
            upload_path = f'/Apps/Feedbackfiles/{new_file_name}'
            self.dbx.files_upload(file_data, upload_path, mode=dropbox.files.WriteMode.overwrite)

            st.success(f"Feedback PDF '{new_file_name}' uploaded successfully to Dropbox.")
        except dropbox.exceptions.ApiError as e:
            st.error(f"Error uploading '{file_name}' to Dropbox: {e}")

```
