### ISSUE TITLE
Visualization Showcase for Homepage

### ISSUE THREAD

**Issue by spaude11** [Isaiahensley/Aquatic-RIG#60]
**Description:**
I will use this issue for my research findings to help making the website more compelling to users as well as meaningful and interactive data and map story. 

**Objective:** 
1. Increase user engagement by providing compelling content, interactive features and visually appealing data and map stories to capture user's attention. 
2. Enhance data visualization: improve the data visualization to make it more understandable, insightful .
3. Foster meaningful Interaction: integrate opportunities for meaningful interaction  by incorporating features such as interactive maps, surveys

**Initial findings:** 
 1. Found some interactive and reference materials in the internet that focused on "Communicating effectively with data"
 2. Interactive map story: Data storytelling technique only by using latitude and longitude technique
 3. We can make a template of map to put as a video and emblem in the app. 

**Steps for investigation:** 
1. Look for a similar website that serves similar purpose as Aquatic RIG. 
2. Research for technique for making story telling data visuals. 
3. Look for ways to integrate the findings into website

**Expected Outcome:** 
1. Proper visuals that will provide users better interaction with the website
2. The website will have more compelling features for clients.
3. Functioning website with interactive and meaningful visuals.

**Comment by spaude11** [comment]
https://helpcenter.flourish.studio/hc/en-us/articles/8827954105999-How-to-create-an-animated-map-story

How to create an animated map story

**Comment by spaude11** [comment]
https://github.com/Isaiahensley/Aquatic-RIG/assets/53842239/02ffd922-e174-4381-a851-7a18b1b8f3f0
I Created one video to put in homepage. I might have to make some adjustments to properly display in the website. I am working on it.

**Comment by spaude11** [comment]
If I work on it i will post something in here as well

**Comment by spaude11** [comment]
https://www.canairyalert.org/demo

**Comment by spaude11** [comment]
isaiah made one good gif to work on, I downloaded and activated Tableau for data visualization

**Comment by spaude11** [comment]
**Description:**
Research findings to help making the website more compelling to users as well as meaningful and interactive data and map story. 

**Objective:** 
1. Increase user engagement by providing compelling content, interactive features and visually appealing data and map stories to capture user's attention. 
2. Enhance data visualization: improve the data visualization to make it more understandable, insightful .
3. Foster meaningful Interaction: integrate opportunities for meaningful interaction  by incorporating features such as interactive maps, surveys


**Initial findings:** 
 1. Isaiah created one gif out of the quiver plot as well as heat map. 
 ![Image](https://github.com/Isaiahensley/Aquatic-RIG/assets/53842239/a7517619-d47b-491d-ab73-4d7f27d62a8d)

 3. Interactive map story: Working with tableau to make more visuals that we might put in website
 
 5. We can make a template of map to put as a video and emblem in the app. **Steps for investigation:** 
1. Work with tableau
2. Generate more gifs or more ideas for making interactive slides of visualized data

**Expected Outcome:** 
1. Proper visuals that will provide users better interaction with the website
2. The website will have more compelling features for clients.
3. Functioning website with interactive and meaningful visuals.

**Comment by spaude11** [comment]
I will add something in this issue

**Comment by blackm61** [comment]
### Description:

I researched how to use gifs in streamlit and added the gifs created from our dataset management page to our homepage.

### Additional context:

The gifs show a good example of the images generated in the dataset management page. We might need to change the gifs in the future, but for now the gifs are working, and are good and accurate examples of visualizations from our dataset management page.

### Screenshot:

![Image](https://github.com/Isaiahensley/Aquatic-RIG/assets/143751284/30ac0ec4-7e95-4a13-9801-45745b612e81)
