### ISSUE TITLE
Homepage Summary Section

### ISSUE THREAD

**Issue by blackm61** [Isaiahensley/Aquatic-RIG#61]
**Description:** 
This issue is for creating a summary on our websites home page. This will be a descriptive summary that explains the purpose of our website, shows examples of our visualization tools, and shows users how to use these tools. This serves as one part of the home page with more features to be added in the future.

**Expectations:**
This should be an informative introduction for new users browsing our website. After seeing this summary users should have a good idea for both the purpose of the website and how to use it.

**Environment Details:**
Pycharm
Python 3
local host streamlit sharing

**Additional context:**
No additional context yet. To be completed.

**Comment by blackm61** [comment]
**Description:**
I've created a summary section for our homepage. The summary states "AquaticRig is a tool for visualizing and analyzing aquatic data. Our website enables researchers,educators, and anyone interested in aquatic science, to explore and understand the complexities of water bodies around the globe." 

As of now I plan to change the font size and the position of the summary on the website. I also plan to add any changes needed to the summary description based on group feedback. 

I also need to provide examples of our visualization tools, and show our users will use the dataset management page. But I am going to make a separate section and cut this off from the description. 

**Expected Outcome:**
A descriptive summary that explains the purpose of our website, shows examples of our visualization tools, and shows users how to use these tools.

**Additional context:**
This is the code for this section of the homepage right now. 

```
` import streamlit as st
 from PIL import Image


 def home_page():

    st.sidebar.markdown("Dataset-Related Links")
    st.sidebar.link_button("GitHub Page", "https://github.com/Isaiahensley/Aquatic-RIG")

    st.sidebar.markdown("Software-Related Links")
    st.sidebar.link_button("Matplotlib", "https://matplotlib.org/")
    st.sidebar.link_button("Streamlit", "https://streamlit.io/")
    st.sidebar.link_button("NumPy", "https://numpy.org/")


    left_col, right_col = st.columns(2)
    with left_col:
        image = Image.open('AquaRigLogo.png')
        st.image(image, width=400, output_format="PNG")

    right_col.markdown("# Aquatic Rig")
    right_col.markdown("### a web application for analyzing and visualizing time-series water data")
    right_col.markdown("")
    right_col.markdown("")
    right_col.markdown("Created by Isaiah Hensley, Maria Black, Sudeep Paudel, Richard Peters")
    right_col.markdown("Louisiana State University Shreveport")


    st.divider()
    st.write("AquaticRig is a tool for visualizing and analyzing aquatic data. Our website enables researchers,"
             "educators, and anyone interested in aquatic science, to explore and understand the complexities of "
             "water bodies around the globe.")`

```


Solution:
Not completed yet.

**Comment by blackm61** [comment]
.

**Comment by blackm61** [comment]
.

**Comment by spaude11** [comment]
It looks good. Its a great description. You can close the issue.
