### ISSUE TITLE
Searching for NC File Datasets

### ISSUE THREAD

**Issue by Isaiahensley** [Isaiahensley/Aquatic-RIG#63]
**Description:**
This issue is for finding more NetCDF4 datasets to test our website with. Currently, we have a repository from the work we are doing with Dr. Alam. However, we want to make our website accept various types of aquatic data .nc files. It may be beneficial to email Dr. Alam for more information if finding .nc files becomes difficult.

**Expectations:**
Look on the internet and find other repositories with aquatic nc files. We ideally want at least 3 additional datasets to work with.

**Current Known Repository:**
This is where we got our original NetCDF4 repository from
https://sccoos.org/roms-model-output/
https://erddap.sccoos.org/erddap/files/roms_fcst/

**Comment by rpeters47** [comment]
Found site with NC files related to Oceans: https://www.ncei.noaa.gov/access/world-ocean-database/bin/getgeodata.pl?Depth=O&WorldOcean.x=546&WorldOcean.y=198

**Comment by spaude11** [comment]
That's great. Do we need more datasets?

**Comment by rpeters47** [comment]
Found a new sources of NC files that don't require conversion.

https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.nodc:NCEI-GOCD

**Comment by Isaiahensley** [comment]
Sorry for the last-minute response. Last night we tested these files Richard found and they are going to be great to test our website with. It contains Ocean data in a different format which lead to me creating the [Compatibility for various NetCDF4 formats](https://github.com/users/Isaiahensley/projects/3/views/6?pane=issue&itemId=54464835) Issue. Thank you so much Richard and I can close this issue for you.
