### ISSUE TITLE
Global Exception Handling and Error Logging

### ISSUE THREAD

**Issue by spaude11** [Isaiahensley/Aquatic-RIG#64]
**Description:** 
The objective of this issue is to create a method for handling errors and exceptional conditions that will occur during the execution of program. The primary objective is to first test the website and check if there are any errors and logs the error into dropbox for later use.

**Steps to Reproduce:** 
Few webpages are working, I will test the website and check the code for Analyze input, Code review, Testing, logging methods. 
 
**Expected Vs Actual Behavior:** 
Test the website and provide the expected and the actual behavior of the program

**Code Snippets:** 
Provide the error prone code from the file

**Environment Details:** 
Pycharm, Streamlit, Github

**For Issue Resolution:** 
Use Try, Except, else and finally block as well as for storing the errors use Logging, Error Messages, Storage

**Comment by spaude11** [comment]
I will edit something for tomorrows standup

**Comment by spaude11** [comment]
I am waiting for the push in the code for testing.

**Comment by spaude11** [comment]
Add something in here after testing

**Comment by spaude11** [comment]
<img width="756" alt="Error for DropBox integration" src="https://github.com/Isaiahensley/Aquatic-RIG/assets/53842239/61d3549d-76f7-4d0e-9d8e-14548773bae4">

**Comment by spaude11** [comment]
<img width="742" alt="DropboxErrorLogging" src="https://github.com/Isaiahensley/Aquatic-RIG/assets/53842239/e21e7e4f-cb54-4e31-9e43-fe6798351360">

**Comment by spaude11** [comment]
updated_error_log.txt

**Comment by spaude11** [comment]
**Description:**
Adding time to the error logging for clear understanding when did the error happened. 

**Steps to Reproduce**
Whenever error happens in the code, it generate a history of error into a file. The file is then sent to dropbox for later review. I wanted to add time into the error log to show when does the error happens

**Expected Vs Actual Behaviour**
The error log was not showing the time behaviour. I changed upload_error_log method in DropBoxLogger class. The error logging is working as expected now. 

<img width="1307" alt="Screenshot 2024-03-05 at 8 53 33 pm" src="https://github.com/Isaiahensley/Aquatic-RIG/assets/53842239/388e71ad-1464-40d7-b673-38502b44cd5e">

**Code Snippets**

```  
       def upload_error_log(self, error_log):
        # Format the current time
        current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Download the existing error log file from Dropbox
        try:
            _, existing_file = self.dbx.files_download('/Apps/Feedbackfiles/error_log.txt')
            existing_error_log = existing_file.content.decode('utf-8')
        except dropbox.exceptions.ApiError:
            existing_error_log = ""

        # Append the new error log with timestamp to the existing content
        updated_error_log = existing_error_log + f"\n{current_time} - {error_log}"

        # Upload the updated error log back to Dropbox
        with open('updated_error_log.txt', 'w') as f:
            f.write(updated_error_log)

        with open('updated_error_log.txt', 'rb') as f:
            try:
                self.dbx.files_upload(f.read(), '/Apps/Feedbackfiles/error_log.txt',
                                      mode=dropbox.files.WriteMode.overwrite)
                print("Error log updated and uploaded successfully to Dropbox.")
            except dropbox.exceptions.ApiError as e:
                print(f"Error updating error log on Dropbox: {e}")
```

**Environment Details**
Pycharm, Streamlit, DropBox

**Issue Resolution**
Added library date time and created method to add the date time into the errors

**Comment by blackm61** [comment]
Great we can close the issue. However later on we'll need to add additional exception to detect more errors that can happen on the website. We can make an issue for this later on as its not too important just yet. This Looks great!
