### ISSUE TITLE
Creating helper tools for selection boxes

### ISSUE THREAD

**Issue by Isaiahensley** [Isaiahensley/Aquatic-RIG#75]
### **Description:**
The goal of this issue is to make the Dataset Management Page easy to use with a simple and intuitive user interface.

--------------------------------
### **Solution:**
1) Add helper tooltips for each of the selectboxes. These should describe the options that are available and how to use them. For example, The "Visualization Option" selectbox could have a help option that displays what each visualization tool is used for with a brief description.
2) Right now everything is thrown at the user on the page, we should make it a step-by-step process that has a "next" and "back" button. The user should start of by selecting if they would like to upload files or use our example dataset. Then, after confirming the files, can be prompted with visualization options etc.
3) Right now the page is empty and the placement of each selection needs to look nice. We should make this page visually look better and come up with ideas on how to improve the look of this page.

--------------------------------
### **Additional context**
This link has the documentation for the selectbox on streamlit. Use this to find more information on help options.
https://docs.streamlit.io/library/api-reference/widgets/st.selectbox

**Comment by Isaiahensley** [comment]
### **Description:**
I created a test streamlit website to figure out how the help popup worked. To make more than one line of text appear I had to do a lot of searching on the internet but I found a post that helped me figure out how to use multiple lines. Before each \n you must have two whitespace in front of it. Seems to be a bug with streamlit but it functions correctly when formatted this way.

-------------------------------
### **Code Snippet:**
```
import streamlit as st


def main():
    st.title("Streamlit Test")

    help_input = (
        "This is the line1  \n"
        "This is the line 2  \n"
        "This is the line 3"
    )

    option = st.selectbox(
        'How would you like to do?',
        ('Email', 'Phone', 'Book'),
        help=help_input
    )


if __name__ == "__main__":
    main()
```
------------------------------
### **Screenshots:**
I wasn't able to take a screenshot when I hovered over the question mark in the top right of the selectbox but I can put several lines of information here. This will be useful for giving descriptions for things like the visualization tools.
![image](https://github.com/Isaiahensley/Aquatic-RIG/assets/143129356/41f8ac41-fdd6-45b3-8c4c-1f94a069fb56)

**Comment by Isaiahensley** [comment]
.

**Comment by Isaiahensley** [comment]
.

**Comment by spaude11** [comment]
Looks great. Make sure to make the issue name that match your goal from the task.
