### ISSUE TITLE
Testing feedback drop box

### ISSUE THREAD

**Issue by spaude11** [Isaiahensley/Aquatic-RIG#86]
**Description:**
We need to make sure that users can submit answers to our feedback page questions and they get sent to the DropBox we set up.

**Expected Outcome:**
All submissions should be sent to the DropBox and can be viewed by our team members.

**Additional context**
After confirming this works as intended, we will want to save the submissions in a .txt file instead as an image.

**Comment by spaude11** [comment]
<img width="516" alt="FeedbackPageWorking" src="https://github.com/Isaiahensley/Aquatic-RIG/assets/53842239/d40fe267-8918-45c6-a669-e5e3e2afbae3">

<img width="756" alt="Error for DropBox integration" src="https://github.com/Isaiahensley/Aquatic-RIG/assets/53842239/8030bad6-cc3b-4e87-bc86-605f6fd45423">

**Comment by spaude11** [comment]
**Descritption:** 
The objective of this issue was to first integrate the method for sending the feedback files to dropbox. I came across one issue while sending the file to the dropbox. 

**Steps to reproduce:**
Run the file in local host. Write the feedback and submit it. If there are no errors then file will be created and sent to the dropbox. If there are issues, the error will be shown below.


**Expected Vs Actual Behaviour:** 
The code was supposed to send the feedback file into the directory. I gave a unique file name based on the user's email address.

 But firstly it was not able to generate the file. Firstly the errror was it wasn't able to generate file but later the file was not able to send in the drop box. 


<img width="1210" alt="Screenshot 2024-03-05 at 8 28 13 pm" src="https://github.com/Isaiahensley/Aquatic-RIG/assets/53842239/74d38bc0-8a12-4a63-868c-5c6dacf33f0c">



**Code Snippets:**


          
  ```
            def upload_file(self, file_data, file_name, st, user_email):
              try:
             # Construct the new filename with the user's email
            new_file_name = f"feedback_report_{user_email}.pdf"

            # Upload the file to Dropbox
            upload_path = f'/Apps/Feedbackfiles/{new_file_name}'
            self.dbx.files_upload(file_data, upload_path)

            st.success(f"Feedback PDF '{new_file_name}' uploaded successfully to Dropbox.")
        except dropbox.exceptions.ApiError as e:
            st.error(f"Error uploading '{file_name}' to Dropbox: {e}")
```



**Environment Details:**
DropBox, Pycharm, Github, Streamlit

For Issue Resolution:

Made some changes on how the file was generated in upload_file class. Now for each unique email address the file will be sent to drop box.

**Comment by blackm61** [comment]
> **Descritption:** The objective of this issue was to first integrate the method for sending the feedback files to dropbox. I came across one issue while sending the file to the dropbox.
> 
> **Steps to reproduce:** Run the file in local host. Write the feedback and submit it. If there are no errors then file will be created and sent to the dropbox. If there are issues, the error will be shown below.
> 
> **Expected Vs Actual Behaviour:** The code was supposed to send the feedback file into the directory. I gave a unique file name based on the user's email address.
> 
> But firstly it was not able to generate the file. Firstly the errror was it wasn't able to generate file but later the file was not able to send in the drop box.
> 
> <img alt="Screenshot 2024-03-05 at 8 28 13 pm" width="1210" src="https://private-user-images.githubusercontent.com/53842239/310340099-74d38bc0-8a12-4a63-868c-5c6dacf33f0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDE1NDMsIm5iZiI6MTcwOTc0MTI0MywicGF0aCI6Ii81Mzg0MjIzOS8zMTAzNDAwOTktNzRkMzhiYzAtOGExMi00YTYzLTg2OGMtNWM2ZGFjZjMzZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE2MDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmOTY1N2JlOTAzMzU3MmNjMjVhMGIzNzA0ZTAxOWFjYzRiYmY3ZGRlZGEyNDAyZDY2ZGViMjBhNWM5NGRjNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D5lbySSIS99LQm-V93eUVhrsxgvC26X1yHcdYrXxObk">
> **Code Snippets:**
> 
> ```
>           def upload_file(self, file_data, file_name, st, user_email):
>             try:
>            # Construct the new filename with the user's email
>           new_file_name = f"feedback_report_{user_email}.pdf"
> 
>           # Upload the file to Dropbox
>           upload_path = f'/Apps/Feedbackfiles/{new_file_name}'
>           self.dbx.files_upload(file_data, upload_path)
> 
>           st.success(f"Feedback PDF '{new_file_name}' uploaded successfully to Dropbox.")
>       except dropbox.exceptions.ApiError as e:
>           st.error(f"Error uploading '{file_name}' to Dropbox: {e}")
> ```
> 
> **Environment Details:** DropBox, Pycharm, Github, Streamlit
> 
> **For Issue Resolution:**
> 
> Made some changes on how the file was generated in upload_file class. Now for each unique email address the file will be sent to drop box.

This is great but it does seem to make an assumption that a person will only ever want to submit feedback once. I think this is fine but just wanted to point it out. I think this is great!

**Comment by blackm61** [comment]
@spaude11 
This is great but it does seem to make an assumption that a person will only ever want to submit feedback once. I think this is fine but just wanted to point it out. I think this is great!
